exports.images = {
    levels: {
        1: "https://i.imgur.com/mVnz5WB.png",
        2: "https://i.imgur.com/T2xAobd.png",
        3: "https://i.imgur.com/CBnAT0e.png",
        4: "https://i.imgur.com/SsEnvfM.png",
        5: "https://i.imgur.com/uZxWwvn.png",
        6: "https://i.imgur.com/lhlj3R8.png",
        7: "https://i.imgur.com/4wmdeIK.png",
        8: "https://i.imgur.com/tcz2Iil.png",
        9: "https://i.imgur.com/XvQC5NJ.png",
        10: "https://i.imgur.com/VHTqdtP.png",
        11: "https://i.imgur.com/f8rzd6c.png",
        12: "https://i.imgur.com/miACjn3.png",
        13: "https://i.imgur.com/8Njn0PB.png",
        14: "https://i.imgur.com/EjrOmts.png",
        15: "https://i.imgur.com/XRZYEwd.png",
        16: "https://i.imgur.com/dTN1bbi.png",
        17: "https://i.imgur.com/ioQO6le.png",
        18: "https://i.imgur.com/qWHIAnX.png",
        19: "https://i.imgur.com/v532waw.png"
    },
    lvlth: {
        1: 'https://i.imgur.com/sIuaSit.png',
        2: 'https://i.imgur.com/i9ySV5r.png',
        3: 'https://i.imgur.com/EhbOmKu.png',
        4: 'https://i.imgur.com/3vylvJ5.png',
        5: 'https://i.imgur.com/03DeNvk.png',
        6: 'https://i.imgur.com/Sy5uiA9.png',
        7: 'https://i.imgur.com/opaOnWk.png',
        8: 'https://i.imgur.com/mxjPugh.png',
        9: 'https://i.imgur.com/rYLAY1E.png',
        10: 'https://i.imgur.com/emcNflV.png',
        11: 'https://i.imgur.com/Y2HIhf2.png',
        12: 'https://i.imgur.com/gsqHRKY.png',
        13: 'https://i.imgur.com/WwLb7eP.png',
        14: 'https://i.imgur.com/wuFzcDK.png',
        15: 'https://i.imgur.com/C1rBhyi.png',
        16: 'https://i.imgur.com/FmDH5i0.png',
        17: 'https://i.imgur.com/yWScBOg.png',
        18: 'https://i.imgur.com/aTu8tQ4.png',
        19: 'https://i.imgur.com/Wnq7Vya.png',
        20: 'https://i.imgur.com/Wnq7Vya.png',
        21: 'https://i.imgur.com/Wnq7Vya.png'
    }
}