exports.tables = {
    settings: {
        "id": "",
        "guildName": "",
        "logChannelID": "",
        "logToChan": "false",
        "debug": "false",
        "modRole": "Modérateurs",
        "adminRole": "Admins",
        "memberRole": "Membres", 
        "modNotifChannel": "notifications-modération" ,
        "welcomeChannel": "accueil",
        "welcomeEnabled": "true",
        "welcomeMemberChannel": "💬général",
        "welcomeMemberEnabled": "true",
        "newsChannel": "📢news",  
        "suggChannel": "💡suggestions",
        "freeVoiceChan": "➕ Créer salon",
        "voiceChansCategory": "🔷Salons vocaux",
        "accueilCategory": "🔷Espace Public",
        "contactChannelFree": "👋contact",
        "contactChannelWaiting": "🔒👋contact",
        "contactChannelInprogress": "🔒👋contact",
        "commandsChannel": "❗alfred",
        "commandsTestChannel": "tests-cmds",
        "AFKChannel": "⌛AFK",
        "quietChannel": "🔈Au calme",
        "gameJoinChannel": "🎮vos-jeux",
        "gameJoinMessage": "",
        "gameCategoryPrefix": "🟧",
        "gameTextPrefix": "💬",
        "gameInfosPrefix": "📌",
        "gameStatusPrefix": "🚥",
        "gameMainRoleColor": "0xF1C40F",
        "gameModRoleColor": "0xCC7900",
        "gamePlayRoleColor": "0xC27C0E",
        "postedCitations": [],
        "postedAstuces": [],
        "mediaPath": "/root/Alfred/media/"
    },
    games: {
        "id": "",
        "name": "default",
        "emoji": "",
        "createdAt": "",
        "actif": false,
        "roleID": "",
        "modRoleID": "",
        "playRoleID": "",
        "categoryID": "",
        "textChannelID": "",
        "infosChannelID": "",
        "statusChannelID": "",
        "voiceChannelID": "",
        "serversStatusMessageID": ""
    },
    gameservers:{
        "id": "default",
        "createdAt": "",
        "createdate": "",
        "createdTime": "",
        "isActive": true,
        "gamename": "",
        "servername": "",
        "ip": "",
        "portrcon": "",
        "portftp": "",
        "pwdrcon": "",
        "pwdftp": "",
        "status": "",
        "steamlink": "",
        "connected": 0,
        "playerlist": []
    },
    gameserversPlayers: {
        "id": "default",
        "steamName": "",
        "memberID": "",
        "firstSeenAt": "",
        "firstSeenDate": "",
        "firstSeenTime": "",
        "lastSeenAt": "",
        "lastSeenDate": "",
        "lastSeenTime": "",
        "isBanned": false
    },
    userdata: {
        "id": "default",
        "username": "",
        "nickname": "",
        "displayName": "",
        "createdAt": "",
        "createdate": "",
        "createdTime": "",
        "joinedAt": "",
        "joinedDate": "",
        "joinedTime": "",
        "level": "",
        "xp": "",
        "logs": []
    },
    userdataLogs: {
        "createdAt": "",
        "createdBy": "",
        "date": "",
        "heure": "",
        "event": "",
        "commentaire": ""
    },
    userdataNicknames:{
        "date": "",
        "oldNickname": "",
        "newNickname": ""
    },
    usergame: {
        "id": "",
        "userid": "",
        "gameid": "",
        "joinedAt": "",
        "joinedDate": "",
        "joinedTime": "",
        "xp": 0,
        "level": "",
        "lastPlayed": "",
        "lastAction": ""
    },
    userxplogs: {
        "id": "",
        "date": "",
        "userid": "",
        "xp": [],
        "gamexp": []
    },
    postedEmbeds: {
        "id": "",
        "name": "default",
        "channelID": "",
        "currentPage": 1,
        "totalPages": "",
        "pages": []
    },
    embeds:{
        "id": "",
        "statut": "",
        "titre": "",
        "createdAt": "",
        "createdDate": "",
        "createdTime": "",
        "createdBy": "",
        "createdByName": "",
        "ownedBy": "",
        "ownedByName": "",
        "changedAt": "",
        "changedDate": "",
        "changedTime": "",
        "changedBy": "",
        "changedByName": "",
        "copyFrom": null,
        "content": "",
        "isNews": false,
        "showTitle": true,
        "showFooter": true
    },
    astuces: {
        "id": "",
        "texte": "",
        "count": 0
    },
    messagesLogs: {
        "messageID": "",
        "channelID": "",
        "createdBy": "",
        "createdByName": "",
        "createdAt": "",
        "createdDate": "",
        "createdTime": ""
    },
    commandsLogs: {
        "messageID": "",
        "command": "",
        "channelID": "",
        "channelType": "",
        "createdBy": "",
        "createdByName": "",
        "createdAt": "",
        "createdDate": "",
        "createdTime": "",
        "content": ""
    }
}