exports.tables = {
    settings: {
        "id": "",
        "guildName": "",
        "logChannelID": "",
        "logToChan": "false",
        "debug": "false",
        "modRole": "",
        "adminRole": "",
        "memberRole": "", 
        "modNotifChannel": "" ,
        "systemNotice": "",
        "welcomeChannel": "",
        "welcomeMessage": "",
        "welcomeEnabled": "",
        "welcomeMemberChannel": "",
        "welcomeMemberMessage": "",
        "welcomeMemberEnabled": "",  
        "freeVoiceChan": "",
        "voiceChansCategory": "",
        "AFKChannel": "",
        "quietChannel": "",
        "gameCategoryPrefix": "",
        "gameTextPrefix": "",
        "gameInfosPrefix": "",
        "gameStatusPrefix": "",
        "gameIdleDays": "1",
        "mediaPath": ""
    }
}